name: "trello-turbo"

services:
  nestjs_dev:
    container_name: "trello-nestjs"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend/src:/app/src

  db:
    image: postgres:13.5
    container_name: "trello-postgres"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - database:/data/database

volumes:
  database: