name: "trello-turbo"

services:
  nestjs_dev:
    container_name: "trello-nestjs"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend/src:/app/src